### ISSUE TITLE
fix to not cause failures when CLEARBIT_KEY isn't set 

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-clearbit#7]
Because the `clearbit` dependency has an `assert` on CLEARBIT_KEY being set, any module that depends on this one, that doesn't have that environment variable set, will fail. 

For example [this Travis build](https://travis-ci.org/activeprospect/leadconduit-integrations/builds/74438495):

```
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: An API key must be provided
  at new ClearbitClient (/home/travis/build/activeprospect/leadconduit-integrations/node_modules/leadconduit-clearbit/node_modules/clearbit/src/client.js:17:3)
  at module.exports (/home/travis/build/activeprospect/leadconduit-integrations/node_modules/leadconduit-clearbit/node_modules/clearbit/src/index.js:6:10)
  at Object.<anonymous> (/home/travis/build/activeprospect/leadconduit-integrations/node_modules/leadconduit-clearbit/lib/person_lookup.js:5:33)
  at Object.<anonymous> (/home/travis/build/activeprospect/leadconduit-integrations/node_modules/leadconduit-clearbit/lib/person_lookup.js:315:4)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/home/travis/build/activeprospect/leadconduit-integrations/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
etc.
```

Once this is fixed, the `CLEARBIT_KEY` setting should be removed from `package.json`.

**Comment by cgrayson** [comment]
Should probably also add a check to `validate()` that the `process.env.` value is set, with a clear message if it's not.
